### ISSUE TITLE
java.io.IOException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by sdvillaruziii** [YE-Fan/JAVA-RTSP-JSMpeg#1]
![image](https://user-images.githubusercontent.com/44084988/84156029-b1d87200-aa71-11ea-8932-b0cdf8621403.png)

**Comment by YE-Fan** [comment]
你是在什么情况下出现这个问题的，能否提供更多的日志信息

**Comment by sdvillaruziii** [comment]
> 你是在什么情况下出现这个问题的，能否提供更多的日志信息

I received this error from @RequestMapping("/upload/{playChannel}") after uploading and playing the stream for about 3-5 minutes.

**Comment by sdvillaruziii** [comment]
> 你是在什么情况下出现这个问题的，能否提供更多的日志信息

I think the problem is in the RtspTransThread. I removed it and it is not closing the stream.

![image](https://user-images.githubusercontent.com/44084988/84234502-0f65d080-aafd-11ea-90bf-73309d7f645e.png)

**Comment by YE-Fan** [comment]
do you POST /stream/play within 60s again？
i think it is not a problem. when you first POST /stream/play, RtspTransThread start a stream.And if you don't POST /stream/play in 60s again,the timer will interrupt the RtspTransThread to stop the stream, then the RtspTransThread  will end,and print these Exception info,it will not crash the program,just print Exception info,i will deal it after.
you should POST /stream/play  maybe every 30s ( less than 60s ).
in demo, you should click the 'play' button every 30s.

**Comment by sdvillaruziii** [comment]
> do you POST /stream/play within 60s again？
> i think it is not a problem. when you first POST /stream/play, RtspTransThread start a stream.And if you don't POST /stream/play in 60s again,the timer will interrupt the RtspTransThread to stop the stream, then the RtspTransThread will end,and print these Exception info,it will not crash the program,just print Exception info,i will deal it after.
> you should POST /stream/play maybe every 30s ( less than 60s ).
> in demo, you should click the 'play' button every 30s.

So basically you need to play every 30s for it to stream without interruption?

**Comment by YE-Fan** [comment]
> 
> 
> > do you POST /stream/play within 60s again？
> > i think it is not a problem. when you first POST /stream/play, RtspTransThread start a stream.And if you don't POST /stream/play in 60s again,the timer will interrupt the RtspTransThread to stop the stream, then the RtspTransThread will end,and print these Exception info,it will not crash the program,just print Exception info,i will deal it after.
> > you should POST /stream/play maybe every 30s ( less than 60s ).
> > in demo, you should click the 'play' button every 30s.
> 
> So basically you need to play every 30s for it to stream without interruption?

yes,this design is for auto close stream,if nobody POST /stream/play 60s,the stream auto close.

**Comment by sdvillaruziii** [comment]
> > > do you POST /stream/play within 60s again？
> > > i think it is not a problem. when you first POST /stream/play, RtspTransThread start a stream.And if you don't POST /stream/play in 60s again,the timer will interrupt the RtspTransThread to stop the stream, then the RtspTransThread will end,and print these Exception info,it will not crash the program,just print Exception info,i will deal it after.
> > > you should POST /stream/play maybe every 30s ( less than 60s ).
> > > in demo, you should click the 'play' button every 30s.
> > 
> > 
> > So basically you need to play every 30s for it to stream without interruption?
> 
> yes,this design is for auto close stream,if nobody POST /stream/play 60s,the stream auto close.

Yes, I saw your code you put a 1 minute interval in timer.
