### ISSUE TITLE
卡顿严重，并且画面一直闪烁

### ISSUE THREAD

**Issue by Alt-er** [YE-Fan/JAVA-RTSP-JSMpeg#2]
卡顿严重，并且画面一直闪烁，是否有什么办法或者思路解决这个问题？

**Comment by YE-Fan** [comment]
如果是在非局域网环境下，考虑一下带宽问题，很可能是服务器的带宽不够，调低摄像头视频流的画面质量。
如果是局域网环境下，top.mihile.cableMonitorMedia.service.RtspTransService这个类里面，调整ffmpeg的参数，ffmpeg的转码参数也会影响画面质量、延迟等。
我在自己是8g内存，i5的cpu，在局域网条件下，是相当顺畅和高清的，公网环境下，我1Mbps的服务器带宽，基本能播放480P的视频质量不卡顿。
当然如果是多路视频转码的话，就需要比较高的机器配置了。

**Comment by Alt-er** [comment]
嗯，我是在局域网环境下测试的，我尝试调整参数测试一下吧。我看到代码里面把声音屏蔽了，如果我把那行代码注释了能否播放声音？因为我这边的rtsp流暂时都没有声音，所以暂时无法测试。

**Comment by YE-Fan** [comment]
我好像代码改动哪里改出问题了，也一直闪烁，声音是故意拿掉的，因为声音好像会影响转码速度，JSMpeg本身对声音的支持好像也有点问题。这块我后面再看一下

**Comment by Alt-er** [comment]
嗯，好的，我在网上也看到说JSMpeg对声音的支持不好，但是都是几年前说的，现在最新的版本应该是没有什么太大问题的。具体还需要测试一下

**Comment by YE-Fan** [comment]
闪烁问题我刚复现了一下，是否是你第一次 rtsp地址哪个输错了，然后又输了正确的地址。举个例子：
rtsp://admin:mihile123@192.168.1.141:554/Streaming/Channels/102
输成了 ip前面加了个$
rtsp://admin:mihile123@$192.168.1.141:554/Streaming/Channels/102
点了play之后，又输了正确的地址再点play
这个时候就会闪烁
刷新一下页面就行，你看看是不是这个问题

**Comment by Alt-er** [comment]
嗯 测试了一下只要输入过无效的或者不可用的地址，后面再输入可用的地址就会出现闪烁

**Comment by YE-Fan** [comment]
卡顿问题还存在吗

**Comment by Alt-er** [comment]
因为我这边的画面几乎是静止的，只有右上角的时间在动，所以卡顿看着不明显，不过我根据时间的跳动频率来看应该是比较稳定的。感谢。

**Comment by YE-Fan** [comment]
> 
> 
> 嗯，我是在局域网环境下测试的，我尝试调整参数测试一下吧。我看到代码里面把声音屏蔽了，如果我把那行代码注释了能否播放声音？因为我这边的rtsp流暂时都没有声音，所以暂时无法测试。

声音功能加上了，现在启动的时候加上 -audio参数可以播放声音，不过延迟可能会稍微增加，具体的声音质量同样的在top.mihile.cableMonitorMedia.service.RtspTransService这个类里面根据实际情况调整参数
